version: '3'
services:
  app:
    container_name: bank_sampah
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql
      - mongodb          
    networks:
      - fullstack


  mysql:
    image: mysql:5.7
    container_name: db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack


  mongodb:
    image: mongo
    container_name: db_mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=bank_sampah
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - database_mongo:/data/db
    networks:
      - fullstack


volumes:
  api:
  database_mysql:
  database_mongo:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge